version: '3'

volumes:
  postgres_volume:

name: local_project

services:
  note-db:
    image: postgres:14.0
    env_file:
      - .env.local
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"

  application:
    build:
      dockerfile: local-server.Dockerfile
    env_file:
      - .env.local
    depends_on:
      - note-db
    ports:
      - "${APP_PORT}:${APP_PORT}"