[tool.pytest.ini_options]
pythonpath = ["."]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "serial",
]

[tool.black]
line-length = 120
exclude = '''
/(
    \.git
  | \.github
  | \.mypy_cache
  | \.pytest_cache
  | \.idea
  | venv
  | venv_linter
  | venv_tests
  | \.local
  | makefile\.inc
  | build
  | dist
)/
'''

[tool.isort]
profile = 'black'
line_length = 120
skip_glob = [
    ".history",
    "venv",
    "venv_linter",
    "venv_tests",
]
use_parentheses = true
multi_line_output = 3
include_trailing_comma = true

[tool.flakeheaven]
exclude = [
    ".history",
    "venv",
    "venv_linter",
    "venv_tests",
]
format = "grouped"
max_line_length = 120
show_source = true
extended_default_ignore = []

[tool.flake8]
per-file-ignores = [
    '__init__.py:F401',
    'test_*.py:F401,F811',
]
max-line-length = 120
count = true