name: python-linters

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
  pull_request:
    branches:
      - main
    paths:
      - "**.py"

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: python linters
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0
      - name: Install linter dependencies
        run: |
          python -m pip install pip==24.0
          pip install -r requirements.txt
      - name: Check for python file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: 'shell'
          filters: |
            py_scripts_filter:
              - added|modified: '**/*.py'
      - name: Run linter
        if: ${{ steps.filter.outputs.py_scripts_filter == 'true' }}
        run: |
          echo "Changed python files: ${{ steps.filter.outputs.py_scripts_filter_files }}"
          flake8 ${{ steps.filter.outputs.py_scripts_filter_files }}
          python -m black --check ${{ steps.filter.outputs.py_scripts_filter_files }}
          python -m isort --check ${{ steps.filter.outputs.py_scripts_filter_files }}